## cluster parameters
cluster_cmd: 'qsub -V -cwd -j y -pe threaded {threads} -l h_vmem={cluster.memory},h_rt=24:00:00 -N {rule}.snakemake -S /bin/bash'
latency_wait: 300
cluster_logDir: cluster_logs
__default__:
    memory: 20G
bwa_map:
    memory: 40G
